name: tests

on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  build:
    strategy:
      matrix:
        config:
        # [Python version, tox env]
        # - ["2.7",   "plone43-py27"]
        # - ["2.7",   "plone50-py27"]
        # - ["2.7",   "plone51-py27"]
        # - ["2.7",   "plone52-py27"]
        - ["3.7",   "plone52-py37"]
        - ["3.8",   "plone52-py38"]
        - ["3.9",   "plone52-py39"]
        - ["3.8",   "plone60-py38"]
        - ["3.9",   "plone60-py39"]
        - ["3.10",   "plone60-py310"]
        - ["3.11",   "plone60-py311"]
        - ["3.12",   "plone60-py312"]
    runs-on: ubuntu-latest
    name: ${{ matrix.config[1] }}
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.config[0] }}
    - name: Pip cache
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ matrix.config[0] }}-${{ hashFiles('setup.*', 'tox.ini') }}
        restore-keys: |
          ${{ runner.os }}-pip-${{ matrix.config[0] }}-
          ${{ runner.os }}-pip-
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install tox
    - name: Test
      run: tox -e ${{ matrix.config[1] }}
    - name: Coveralls
      uses: AndreMiras/coveralls-python-action@develop
      with:
        parallel: true
        flag-name: ${{ matrix.config[1] }}

  coveralls_finish:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Coveralls Finished
      uses: AndreMiras/coveralls-python-action@develop
      with:
        parallel-finished: true
